"use strict";
/* ================= LESSON DATA =================
   Mayamalavagowla: S R1 G3 M1 P D1 N3. "'" = upper octave, "''" = two octaves up.
   Keep arrays editable — titles/subs are display-only. */
const LESSONS = [
{
  id: "sarali", name: "Sarali Varisai", num: 1,
  desc: "14 patterns · straight swara sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Simple ascent / descent", sub: "Simple ascent / descent", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "2 \u00b7 Focus on R and N", sub: "Focus on R and N", notes: ["S", "R1", "S", "R1", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "S'", "N3", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "3 \u00b7 Focus on G and D", sub: "Focus on G and D", notes: ["S", "R1", "G3", "S", "R1", "G3", "S", "R1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "S'", "N3", "D1", "S'", "N3", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "4 \u00b7 Focus on M and P", sub: "Focus on M and P", notes: ["S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "5 \u00b7 Focus on P and M (dheergam);", sub: "Focus on P and M (dheergam); R, N", notes: ["S", "R1", "G3", "M1", "P", "-", "S", "R1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "-", "S'", "N3", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "6 \u00b7 Focus on G and D", sub: "Focus on G and D", notes: ["S", "R1", "G3", "M1", "P", "D1", "S", "R1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "G3", "S'", "N3", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "7 \u00b7 Focus on N and R (dheergam)", sub: "Focus on N and R (dheergam)", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "-", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "G3", "R1", "-", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "8 \u00b7 Zigzag", sub: "Zigzag: P M G R / M P D N", notes: ["S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "9 \u00b7 Zigzag", sub: "Zigzag: P M D P / M P G M", notes: ["S", "R1", "G3", "M1", "P", "M1", "D1", "P", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "M1", "P", "G3", "M1", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "10 \u00b7 Dheergam", sub: "Dheergam: upper tetrachord", notes: ["S", "R1", "G3", "M1", "P", "-", "G3", "M1", "P", "-", "-", "-", "P", "-", "-", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "11 \u00b7 Dheergam from upper octave", sub: "Dheergam from upper octave", notes: ["S'", "-", "N3", "D1", "N3", "-", "D1", "P", "D1", "-", "P", "M1", "P", "-", "P", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "12 \u00b7 Doubled notes, upper octave,", sub: "Doubled notes, upper octave, dheergam", notes: ["S'", "S'", "N3", "D1", "N3", "N3", "D1", "P", "D1", "D1", "P", "M1", "P", "-", "P", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "13 \u00b7 Dheergam focus", sub: "Dheergam focus: G, P, D; region M-N; zigzag emphasis, D-notes", notes: ["S", "R1", "G3", "R1", "G3", "-", "G3", "M1", "P", "M1", "P", "-", "D1", "P", "D1", "-", "M1", "P", "D1", "P", "D1", "N3", "D1", "P", "M1", "P", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "14 \u00b7 Dheergam pairs to upper octa", sub: "Dheergam pairs to upper octave", notes: ["S", "R1", "G3", "M1", "P", "-", "P", "-", "D1", "D1", "P", "-", "M1", "M1", "P", "-", "D1", "N3", "S'", "-", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] }
  ] }
,
{
  id: "janta", name: "Janta Varisai", num: 2,
  desc: "8 patterns \u00b7 doubled-note (janta) sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Doubled scale, up and down", sub: "Doubled scale, up and down", notes: ["S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "2 \u00b7 Sliding doubled pairs", sub: "Sliding doubled pairs", notes: ["S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "3 \u00b7 Janta focus on each swara (with gap)", sub: "Janta focus on each swara (with gap)", notes: ["S", "S", "R1", "S", "S", "R1", "S", "R1", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "G3", "R1", "R1", "G3", "R1", "G3", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "M1", "G3", "G3", "M1", "G3", "M1", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "P", "M1", "M1", "P", "M1", "P", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "D1", "-", "P", "P", "D1", "P", "D1", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "N3", "S'", "S'", "N3", "S'", "N3", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "D1", "N3", "N3", "D1", "N3", "D1", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "P", "D1", "D1", "P", "D1", "P", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "M1", "P", "P", "M1", "P", "M1", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "G3", "M1", "M1", "G3", "M1", "G3", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "4 \u00b7 Janta focus per swara, variant (with gap)", sub: "Janta focus per swara, variant (with gap)", notes: ["S", "S", "R1", "R1", "G3", "S", "R1", "G3", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "G3", "G3", "M1", "R1", "G3", "M1", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "M1", "M1", "P", "G3", "M1", "P", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "P", "P", "D1", "M1", "P", "D1", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "D1", "D1", "N3", "-", "P", "D1", "N3", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "N3", "N3", "D1", "S'", "N3", "D1", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "D1", "D1", "P", "N3", "D1", "P", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "P", "P", "M1", "D1", "P", "M1", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "M1", "M1", "G3", "P", "M1", "G3", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "G3", "G3", "R1", "M1", "G3", "R1", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "5 \u00b7 Janta with dheergam rests", sub: "Janta with dheergam rests", notes: ["S", "S", "-", "R1", "R1", "-", "G3", "G3", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "-", "G3", "G3", "-", "M1", "M1", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "-", "M1", "M1", "-", "P", "P", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "-", "P", "P", "-", "D1", "D1", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "-", "D1", "D1", "-", "N3", "N3", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "-", "N3", "N3", "-", "D1", "D1", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "-", "D1", "D1", "-", "P", "P", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "-", "P", "P", "-", "M1", "M1", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "-", "M1", "M1", "-", "G3", "G3", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "-", "G3", "G3", "-", "R1", "R1", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "6 \u00b7 Janta with dheergam rests, variant", sub: "Janta with dheergam rests, variant", notes: ["S", "-", "S", "R1", "-", "R1", "G3", "G3", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "-", "R1", "G3", "-", "G3", "M1", "M1", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "-", "G3", "M1", "-", "M1", "P", "P", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "-", "M1", "P", "-", "P", "D1", "D1", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "-", "P", "D1", "-", "D1", "N3", "N3", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "-", "S'", "N3", "-", "N3", "D1", "D1", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "-", "N3", "D1", "-", "D1", "P", "P", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "-", "D1", "P", "-", "P", "M1", "M1", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "-", "P", "M1", "-", "M1", "G3", "G3", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "-", "M1", "G3", "-", "G3", "R1", "R1", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "7 \u00b7 Triple janta", sub: "Triple janta", notes: ["S", "S", "S", "R1", "R1", "R1", "G3", "G3", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "R1", "G3", "G3", "G3", "M1", "M1", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "G3", "M1", "M1", "M1", "P", "P", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "M1", "P", "P", "P", "D1", "D1", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "P", "D1", "D1", "D1", "N3", "N3", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "S'", "N3", "N3", "N3", "D1", "D1", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "N3", "D1", "D1", "D1", "P", "P", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "D1", "P", "P", "P", "M1", "M1", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "P", "M1", "M1", "M1", "G3", "G3", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "M1", "G3", "G3", "G3", "R1", "R1", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] },
    { title: "8 \u00b7 Janta jumps", sub: "Janta jumps", notes: ["S", "S", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "R1", "R1", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "G3", "G3", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "M1", "M1", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "P", "P", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "S'", "S'", "P", "P", "D1", "D1", "N3", "N3", "S'", "S'", "N3", "N3", "D1", "D1", "P", "P", "N3", "N3", "M1", "M1", "P", "P", "D1", "D1", "N3", "N3", "D1", "D1", "P", "P", "M1", "M1", "D1", "D1", "G3", "G3", "M1", "M1", "P", "P", "D1", "D1", "P", "P", "M1", "M1", "G3", "G3", "P", "P", "R1", "R1", "G3", "G3", "M1", "M1", "P", "P", "M1", "M1", "G3", "G3", "R1", "R1", "M1", "M1", "S", "S", "R1", "R1", "G3", "G3", "M1", "M1", "G3", "G3", "R1", "R1", "S", "S"] }
  ]
}
,
{
  id: "dhattu", name: "Dhattu Varisai", num: 3,
  desc: "2 patterns \u00b7 jumping (dhattu) zigzag sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Zigzag chain I", sub: "Zigzag chain I", notes: ["S", "R1", "S", "G3", "R1", "G3", "R1", "M1", "S", "M1", "G3", "R1", "S", "R1", "G3", "M1", "R1", "G3", "R1", "M1", "G3", "M1", "G3", "P", "R1", "P", "M1", "G3", "R1", "G3", "M1", "P", "G3", "M1", "G3", "P", "M1", "P", "M1", "D1", "G3", "D1", "P", "M1", "G3", "M1", "P", "D1", "M1", "P", "M1", "D1", "P", "D1", "P", "N3", "M1", "N3", "D1", "P", "M1", "P", "D1", "N3", "P", "D1", "P", "N3", "D1", "N3", "D1", "S'", "P", "S'", "N3", "D1", "P", "D1", "N3", "S'", "S'", "N3", "S'", "D1", "N3", "D1", "N3", "P", "S'", "P", "D1", "N3", "S'", "N3", "D1", "P", "N3", "D1", "N3", "P", "D1", "P", "D1", "M1", "N3", "M1", "P", "D1", "N3", "D1", "P", "M1", "D1", "P", "D1", "M1", "P", "M1", "P", "G3", "D1", "G3", "M1", "P", "D1", "P", "M1", "G3", "P", "M1", "P", "G3", "M1", "G3", "M1", "R1", "P", "R1", "G3", "M1", "P", "M1", "G3", "R1", "M1", "G3", "M1", "R1", "G3", "R1", "G3", "S", "M1", "S", "R1", "G3", "M1", "G3", "R1", "S"] },
    { title: "2 \u00b7 Zigzag chain II", sub: "Zigzag chain II", notes: ["S", "M1", "G3", "M1", "R1", "G3", "S", "R1", "S", "G3", "R1", "G3", "S", "R1", "G3", "M1", "R1", "P", "M1", "P", "G3", "M1", "R1", "G3", "R1", "M1", "G3", "M1", "R1", "G3", "M1", "P", "G3", "D1", "P", "D1", "M1", "P", "G3", "M1", "G3", "P", "M1", "P", "G3", "M1", "P", "D1", "M1", "N3", "D1", "N3", "P", "D1", "M1", "P", "M1", "D1", "P", "D1", "M1", "P", "D1", "N3", "P", "S'", "N3", "S'", "D1", "N3", "P", "D1", "P", "N3", "D1", "N3", "P", "D1", "N3", "S'", "S'", "P", "D1", "P", "N3", "D1", "S'", "N3", "S'", "D1", "N3", "D1", "S'", "N3", "D1", "P", "N3", "M1", "P", "M1", "D1", "P", "N3", "D1", "N3", "P", "D1", "P", "N3", "D1", "P", "M1", "D1", "G3", "M1", "G3", "P", "M1", "D1", "P", "D1", "M1", "P", "M1", "D1", "P", "M1", "G3", "P", "R1", "G3", "R1", "M1", "G3", "P", "M1", "P", "G3", "M1", "G3", "P", "M1", "G3", "R1", "M1", "S", "R1", "S", "G3", "R1", "M1", "G3", "M1", "R1", "G3", "R1", "M1", "G3", "R1", "S"] }
  ]
}
,
{
  id: "alankaram", name: "Sapta Tala Alankarams", num: 4,
  desc: "7 alankarams \u00b7 one per tala", raga: "Mayamalavagowla",
  patterns: [
    { title: "Dhruva", sub: "Chatusra jati \u00b7 14 aksharas \u00b7 I4 O I4 I4", notes: ["S", "R1", "G3", "M1", "G3", "R1", "S", "R1", "G3", "R1", "S", "R1", "G3", "M1", "R1", "G3", "M1", "P", "M1", "G3", "R1", "G3", "M1", "G3", "R1", "G3", "M1", "P", "G3", "M1", "P", "D1", "P", "M1", "G3", "M1", "P", "M1", "G3", "M1", "P", "D1", "M1", "P", "D1", "N3", "D1", "P", "M1", "P", "D1", "P", "M1", "P", "D1", "N3", "P", "D1", "N3", "S'", "N3", "D1", "P", "D1", "N3", "D1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "D1", "N3", "S'", "N3", "D1", "N3", "S'", "N3", "D1", "P", "N3", "D1", "P", "M1", "P", "D1", "N3", "D1", "P", "D1", "N3", "D1", "P", "M1", "D1", "P", "M1", "G3", "M1", "P", "D1", "P", "M1", "P", "D1", "P", "M1", "G3", "P", "M1", "G3", "R1", "G3", "M1", "P", "M1", "G3", "M1", "P", "M1", "G3", "R1", "M1", "G3", "R1", "S", "R1", "G3", "M1", "G3", "R1", "G3", "M1", "G3", "R1", "S"] },
    { title: "Matya", sub: "Chatusra jati \u00b7 10 aksharas \u00b7 I4 O I4", notes: ["S", "R1", "G3", "R1", "S", "R1", "S", "R1", "G3", "M1", "R1", "G3", "M1", "G3", "R1", "G3", "R1", "G3", "M1", "P", "G3", "M1", "P", "M1", "G3", "M1", "G3", "M1", "P", "D1", "M1", "P", "D1", "P", "M1", "P", "M1", "P", "D1", "N3", "P", "D1", "N3", "D1", "P", "D1", "P", "D1", "N3", "S'", "S'", "N3", "D1", "N3", "S'", "N3", "S'", "N3", "D1", "P", "N3", "D1", "P", "D1", "N3", "D1", "N3", "D1", "P", "M1", "D1", "P", "M1", "P", "D1", "P", "D1", "P", "M1", "G3", "P", "M1", "G3", "M1", "P", "M1", "P", "M1", "G3", "R1", "M1", "G3", "R1", "G3", "M1", "G3", "M1", "G3", "R1", "S"] },
    { title: "Rupaka", sub: "Chatusra jati \u00b7 6 aksharas \u00b7 O I4", notes: ["S", "R1", "S", "R1", "G3", "M1", "R1", "G3", "R1", "G3", "M1", "P", "G3", "M1", "G3", "M1", "P", "D1", "M1", "P", "M1", "P", "D1", "N3", "P", "D1", "P", "D1", "N3", "S'", "S'", "N3", "S'", "N3", "D1", "P", "N3", "D1", "N3", "D1", "P", "M1", "D1", "P", "D1", "P", "M1", "G3", "P", "M1", "P", "M1", "G3", "R1", "M1", "G3", "M1", "G3", "R1", "S"] },
    { title: "Jhampa", sub: "Misra jati \u00b7 10 aksharas \u00b7 I7 U O", notes: ["S", "R1", "G3", "S", "R1", "S", "R1", "G3", "M1", "-", "R1", "G3", "M1", "R1", "G3", "R1", "G3", "M1", "P", "-", "G3", "M1", "P", "G3", "M1", "G3", "M1", "P", "D1", "-", "M1", "P", "D1", "M1", "P", "M1", "P", "D1", "N3", "-", "P", "D1", "N3", "P", "D1", "P", "D1", "N3", "S'", "-", "S'", "N3", "D1", "S'", "N3", "S'", "N3", "D1", "P", "-", "N3", "D1", "P", "N3", "D1", "N3", "D1", "P", "M1", "-", "D1", "P", "M1", "D1", "P", "D1", "P", "M1", "G3", "-", "P", "M1", "G3", "P", "M1", "P", "M1", "G3", "R1", "-", "M1", "G3", "R1", "M1", "G3", "M1", "G3", "R1", "S"] },
    { title: "Triputa", sub: "Tisra jati \u00b7 7 aksharas \u00b7 I3 O O", notes: ["S", "R1", "G3", "S", "R1", "G3", "M1", "R1", "G3", "M1", "R1", "G3", "M1", "P", "G3", "M1", "P", "G3", "M1", "P", "D1", "M1", "P", "D1", "M1", "P", "D1", "N3", "P", "D1", "N3", "P", "D1", "N3", "S'", "S'", "N3", "D1", "S'", "N3", "D1", "P", "N3", "D1", "P", "N3", "D1", "P", "M1", "D1", "P", "M1", "D1", "P", "M1", "G3", "P", "M1", "G3", "P", "M1", "G3", "R1", "M1", "G3", "R1", "M1", "G3", "R1", "S"] },
    { title: "Ata", sub: "Khanda jati \u00b7 14 aksharas \u00b7 I5 I5 O O", notes: ["S", "R1", "-", "G3", "-", "S", "-", "R1", "G3", "-", "M1", "-", "M1", "-", "R1", "G3", "-", "M1", "-", "R1", "-", "G3", "M1", "-", "P", "-", "P", "-", "G3", "M1", "-", "P", "-", "G3", "-", "M1", "P", "-", "D1", "-", "D1", "-", "M1", "P", "-", "D1", "-", "M1", "-", "P", "D1", "-", "N3", "-", "N3", "-", "P", "D1", "-", "N3", "-", "P", "-", "D1", "N3", "-", "S'", "-", "S'", "-", "S'", "N3", "-", "D1", "-", "S'", "-", "N3", "D1", "-", "P", "-", "P", "-", "N3", "D1", "-", "P", "-", "N3", "-", "D1", "P", "-", "M1", "-", "M1", "-", "D1", "P", "-", "M1", "-", "D1", "-", "P", "M1", "-", "G3", "-", "G3", "-", "P", "M1", "-", "G3", "-", "P", "-", "M1", "G3", "-", "R1", "-", "R1", "-", "M1", "G3", "-", "R1", "-", "M1", "-", "G3", "R1", "-", "S", "-", "S", "-"] },
    { title: "Eka", sub: "Chatusra jati \u00b7 4 aksharas \u00b7 I4", notes: ["S", "R1", "G3", "M1", "R1", "G3", "M1", "P", "G3", "M1", "P", "D1", "M1", "P", "D1", "N3", "P", "D1", "N3", "S'", "S'", "N3", "D1", "P", "N3", "D1", "P", "M1", "D1", "P", "M1", "G3", "P", "M1", "G3", "R1", "M1", "G3", "R1", "S"] }
  ]
}
,
{
  id: "mandhra", name: "Mandhra Sthayi Varisai", num: 5,
  desc: "5 patterns \u00b7 lower octave sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Dheergam anchor, expanding phrases", sub: "Lower octave", notes: ["S'", "N3", "D1", "P", "M1", "G3", "R1", "S", "S", "-", "-", "-", "S", "-", "-", "-", "G3", "R1", "S", ",N3", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'"] },
    { title: "2 \u00b7 Dheergam anchor, expanding phrases", sub: "Lower octave", notes: ["S'", "N3", "D1", "P", "M1", "G3", "R1", "S", "S", "-", "-", "-", "S", "-", "-", "-", "G3", "R1", "S", ",N3", "S", "S", ",N3", "S", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'"] },
    { title: "3 \u00b7 Dheergam anchor, expanding phrases", sub: "Lower octave", notes: ["S'", "N3", "D1", "P", "M1", "G3", "R1", "S", "S", "-", "-", "-", "S", "-", "-", "-", "G3", "R1", "S", ",N3", ",D1", ",N3", "S", ",N3", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "S", ",N3", "S", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'"] },
    { title: "4 \u00b7 Dheergam anchor, expanding phrases", sub: "Lower octave", notes: ["S'", "N3", "D1", "P", "M1", "G3", "R1", "S", "S", "-", "-", "-", "S", "-", "-", "-", "G3", "R1", "S", ",N3", ",D1", ",P", "D1", ",N3", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", ",D1", ",N3", "S", ",N3", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "S", ",N3", "S", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'"] },
    { title: "5 \u00b7 Dheergam anchor, expanding phrases", sub: "Lower octave", notes: ["S'", "N3", "D1", "P", "M1", "G3", "R1", "S", "S", "-", "-", "-", "S", "-", "-", "-", "G3", "R1", "S", ",N3", ",D1", ",P", ",M1", ",P", "D1", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", ",D1", ",P", "D1", ",N3", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", ",D1", ",N3", "S", ",N3", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "S", ",N3", "S", "S", ",N3", "S", "R1", "G3", "M1", "P", "M1", "G3", "R1", "S", ",N3", "S", "R1", "G3", "M1", "S", "R1", "G3", "M1", "P", "D1", "N3", "S'"] }
  ]
}
,
{
  id: "madhya", name: "Madhya Sthayi Varisai", num: 6,
  desc: "5 patterns \u00b7 middle octave sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Middle-register phrases", sub: "Middle octave", notes: ["S", "R1", "G3", "M1", "P", "-", "G3", "M1", "P", "-", "-", "-", "P", "-", "-", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "2 \u00b7 Middle-register phrases", sub: "Middle octave", notes: ["S'", "-", "N3", "D1", "N3", "-", "D1", "P", "D1", "-", "P", "M1", "P", "-", "P", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "3 \u00b7 Middle-register phrases", sub: "Middle octave", notes: ["S'", "S'", "N3", "D1", "N3", "N3", "D1", "P", "D1", "D1", "P", "M1", "P", "-", "P", "-", "G3", "M1", "P", "D1", "N3", "D1", "P", "M1", "G3", "M1", "P", "G3", "M1", "G3", "R1", "S"] },
    { title: "4 \u00b7 Middle-register phrases", sub: "Middle octave", notes: ["S", "R1", "G3", "R1", "G3", "-", "G3", "M1", "P", "M1", "P", "-", "D1", "P", "D1", "-", "M1", "P", "D1", "P", "D1", "N3", "D1", "P", "M1", "P", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "5 \u00b7 Middle-register phrases", sub: "Middle octave", notes: ["S", "R1", "G3", "M1", "P", "-", "P", "-", "D1", "D1", "P", "-", "M1", "M1", "P", "-", "D1", "N3", "S'", "-", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] }
  ]
}
,
{
  id: "mel", name: "Mel Sthayi Varisai", num: 7,
  desc: "5 patterns \u00b7 upper octave sequences", raga: "Mayamalavagowla",
  patterns: [
    { title: "1 \u00b7 Dheergam anchor, expanding phrases", sub: "Upper octave", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "-", "-", "-", "S'", "-", "-", "-", "D1", "N3", "S'", "R1'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "2 \u00b7 Dheergam anchor, expanding phrases", sub: "Upper octave", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "-", "-", "-", "S'", "-", "-", "-", "D1", "N3", "S'", "R1'", "S'", "S'", "R1'", "S'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "3 \u00b7 Dheergam anchor, expanding phrases", sub: "Upper octave", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "-", "-", "-", "S'", "-", "-", "-", "D1", "N3", "S'", "R1'", "G3'", "R1'", "S'", "R1'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "S'", "R1'", "S'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "4 \u00b7 Dheergam anchor, expanding phrases", sub: "Upper octave", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "-", "-", "-", "S'", "-", "-", "-", "D1", "N3", "S'", "R1'", "G3'", "M1'", "G3'", "R1'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "G3'", "R1'", "S'", "R1'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "S'", "R1'", "S'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] },
    { title: "5 \u00b7 Dheergam anchor, expanding phrases", sub: "Upper octave", notes: ["S", "R1", "G3", "M1", "P", "D1", "N3", "S'", "S'", "-", "-", "-", "S'", "-", "-", "-", "D1", "N3", "S'", "R1'", "G3'", "M1'", "P'", "M1'", "G3'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "G3'", "M1'", "G3'", "R1'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "G3'", "R1'", "S'", "R1'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "S'", "R1'", "S'", "S'", "R1'", "S'", "N3", "D1", "P", "M1", "P", "D1", "N3", "S'", "R1'", "S'", "N3", "D1", "P", "S'", "N3", "D1", "P", "M1", "G3", "R1", "S"] }
  ]
}
]
